# Generated by Django 5.0 on 2024-01-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Порядковый номер')),
                ('title', models.CharField(max_length=150, verbose_name='Образовательный модуль')),
                ('description', models.TextField(verbose_name='Описание модуля')),
            ],
            options={
                'verbose_name': 'образовательный модуль',
                'verbose_name_plural': 'образовательные модули',
            },
        ),
    ]
